// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyiygiwcirzrgeeehauj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5aXlnaXdjaXJ6cmdlZWVoYXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDk1MDMsImV4cCI6MjA2NjE4NTUwM30.z-fNURrufX8Ev-1cxWVBQq93T7PXbvNk4OAVL4ZB7Vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);